    const circle = [{
        color:'yellow',
        x:5,
        y:80,
        degree:-60,
        size:1
    },{
        color:'yellow',
        x:90,
        y:34,
        degree:180,
        size:2
    },{
        color:'white',
        x:34,
        y:81,
        degree:34,
        size:2
    },{
        color:'yellow',
        x:62,
        y:62,
        degree:90,
        size:2
    },{
        color:'white',
        x:3,
        y:4,
        degree:-90,
        size:3
    },{
        color:'white',
        x:66,
        y:0,
        degree:130,
        size:2
    },{
        color:'white',
        x:90,
        y:34,
        degree:108,
        size:2
    },{
        color:'yellow',
        x:65,
        y:73,
        degree:200,
        size:3
    },{
        color:'yellow',
        x:99,
        y:1,
        degree:160,
        size:2
    },{
        color:'white',
        x:68,
        y:40,
        degree:-30,
        size:2
    },{
        color:'white',
        x:85,
        y:21,
        degree:34,
        size:2
    },{
        color:'yellow',
        x:98,
        y:41,
        degree:223,
        size:2
    },{
        color:'white',
        x:14,
        y:28,
        degree:34,
        size:2
    },{
        color:'yellow',
        x:5,
        y:25,
        degree:102,
        size:2
    },{
        color:'yellow',
        x:47,
        y:18,
        degree:60,
        size:2
    },{
        color:'yellow',
        x:68,
        y:4,
        degree:210,
        size:3
    },{
        color:'yellow',
        x:49,
        y:73,
        degree:2,
        size:2
    },{
        color:'white',
        x:57,
        y:83,
        degree:117,
        size:2
    },{
        color:'yellow',
        x:88,
        y:13,
        degree:34,
        size:2
    },{
        color:'white',
        x:59,
        y:66,
        degree:77,
        size:1
    },{
        color:'white',
        x:94,
        y:57,
        degree:34,
        size:2
    },{
        color:'white',
        x:5,
        y:52,
        degree:34,
        size:2
    }];

    
    export default circle;